// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cprod
NumericMatrix cprod(NumericMatrix X, NumericMatrix Y, bool summit, bool transposeX, bool transposeY);
RcppExport SEXP riskScore_cprod(SEXP XSEXP, SEXP YSEXP, SEXP summitSEXP, SEXP transposeXSEXP, SEXP transposeYSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< bool >::type summit(summitSEXP);
    Rcpp::traits::input_parameter< bool >::type transposeX(transposeXSEXP);
    Rcpp::traits::input_parameter< bool >::type transposeY(transposeYSEXP);
    __result = Rcpp::wrap(cprod(X, Y, summit, transposeX, transposeY));
    return __result;
END_RCPP
}
