# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Colsums of crossprod
#'
#' @description Fast computation of X %*% Y and colSums(X%*%Y)
#' @param X A matrix with dimensions k*n.
#' @param Y A matrix with dimenions n*m.
#' @param summit Logical. If \code{TRUE} return colsums of the resulting matrix.
#' @param transposeX Logical. If \code{TRUE} transpose X before multiplication.
#' @param transposeY Logical. If \code{TRUE} transpose Y before multiplication.
#' @return If \code{summit=0} a matrix with dimensions k * m else a vector of length m.
#' @author Thomas Alexander Gerds <tag@@biostat.ku.dk>
#' @export
colSumsCrossprod <- function(X, Y, transposeY) {
    .Call('riskScore_colSumsCrossprod', PACKAGE = 'riskScore', X, Y, transposeY)
}

#' @export
rowSumsCrossprod <- function(X, Y, transposeY) {
    .Call('riskScore_rowSumsCrossprod', PACKAGE = 'riskScore', X, Y, transposeY)
}

